package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CentarZaPomoc implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Centar pomoci ID")
   private java.lang.Long centarPomociId;
   @org.kie.api.definition.type.Label(value = "Broj Telefona")
   private java.lang.String brojTelefona;

   public CentarZaPomoc()
   {
   }

   public java.lang.Long getCentarPomociId()
   {
      return this.centarPomociId;
   }

   public void setCentarPomociId(java.lang.Long centarPomociId)
   {
      this.centarPomociId = centarPomociId;
   }

   public java.lang.String getBrojTelefona()
   {
      return this.brojTelefona;
   }

   public void setBrojTelefona(java.lang.String brojTelefona)
   {
      this.brojTelefona = brojTelefona;
   }

   public CentarZaPomoc(java.lang.Long centarPomociId,
         java.lang.String brojTelefona)
   {
      this.centarPomociId = centarPomociId;
      this.brojTelefona = brojTelefona;
   }

}