package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CentarZaPomoc implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CentarZaPomoc() {
    }

}