package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cloud implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Cloud ID")
   private java.lang.Long cloudId;
   @org.kie.api.definition.type.Label(value = "Stanje korisnika ID")
   private java.lang.Long stanjeKorisnikaId;

   public Cloud()
   {
   }

   public java.lang.Long getCloudId()
   {
      return this.cloudId;
   }

   public void setCloudId(java.lang.Long cloudId)
   {
      this.cloudId = cloudId;
   }

   public java.lang.Long getStanjeKorisnikaId()
   {
      return this.stanjeKorisnikaId;
   }

   public void setStanjeKorisnikaId(java.lang.Long stanjeKorisnikaId)
   {
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

   public Cloud(java.lang.Long cloudId, java.lang.Long stanjeKorisnikaId)
   {
      this.cloudId = cloudId;
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

}