package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cloud implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Cloud() {
    }

}