package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HitnaPomoc implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Hitna pomoc ID")
   private java.lang.Long hitnaPomocId;
   @org.kie.api.definition.type.Label(value = "GPS Lokacija ID")
   private java.lang.Long gpsLokacijaId;

   public HitnaPomoc()
   {
   }

   public java.lang.Long getHitnaPomocId()
   {
      return this.hitnaPomocId;
   }

   public void setHitnaPomocId(java.lang.Long hitnaPomocId)
   {
      this.hitnaPomocId = hitnaPomocId;
   }

   public java.lang.Long getGpsLokacijaId()
   {
      return this.gpsLokacijaId;
   }

   public void setGpsLokacijaId(java.lang.Long gpsLokacijaId)
   {
      this.gpsLokacijaId = gpsLokacijaId;
   }

   public HitnaPomoc(java.lang.Long hitnaPomocId, java.lang.Long gpsLokacijaId)
   {
      this.hitnaPomocId = hitnaPomocId;
      this.gpsLokacijaId = gpsLokacijaId;
   }

}