package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Izvjestaj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Izvjestaj ID")
   private java.lang.Long izvjestajId;
   @org.kie.api.definition.type.Label("Stanje korisnika ID")
   private StanjeKorisnika stanjeKorisnikaId;

   public Izvjestaj()
   {
   }

   public java.lang.Long getIzvjestajId()
   {
      return this.izvjestajId;
   }

   public void setIzvjestajId(java.lang.Long izvjestajId)
   {
      this.izvjestajId = izvjestajId;
   }

   public streseeg.streseeg.StanjeKorisnika getStanjeKorisnikaId()
   {
      return this.stanjeKorisnikaId;
   }

   public void setStanjeKorisnikaId(
         streseeg.streseeg.StanjeKorisnika stanjeKorisnikaId)
   {
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

   public Izvjestaj(java.lang.Long izvjestajId,
         streseeg.streseeg.StanjeKorisnika stanjeKorisnikaId)
   {
      this.izvjestajId = izvjestajId;
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

}