package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Izvjestaj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Izvjestaj ID")
   private java.lang.Long izvjestajId;
   @org.kie.api.definition.type.Label(value = "Stanje korisnika ID")
   private java.lang.Long stanjeKorisnikaId;

   public Izvjestaj()
   {
   }

   public java.lang.Long getIzvjestajId()
   {
      return this.izvjestajId;
   }

   public void setIzvjestajId(java.lang.Long izvjestajId)
   {
      this.izvjestajId = izvjestajId;
   }

   public java.lang.Long getStanjeKorisnikaId()
   {
      return this.stanjeKorisnikaId;
   }

   public void setStanjeKorisnikaId(java.lang.Long stanjeKorisnikaId)
   {
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

   public Izvjestaj(java.lang.Long izvjestajId,
         java.lang.Long stanjeKorisnikaId)
   {
      this.izvjestajId = izvjestajId;
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

}