package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Izvjestaj implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Izvjestaj ID")
   private Integer izvjestajId;
   @org.kie.api.definition.type.Label(value = "Stanje korisnika FK")
   private streseeg.streseeg.StanjeKorisnika stanjeKorisnika_fk;

   public Izvjestaj()
   {
   }

   public java.lang.Integer getIzvjestajId()
   {
      return this.izvjestajId;
   }

   public void setIzvjestajId(java.lang.Integer izvjestajId)
   {
      this.izvjestajId = izvjestajId;
   }

   public streseeg.streseeg.StanjeKorisnika getStanjeKorisnika_fk()
   {
      return this.stanjeKorisnika_fk;
   }

   public void setStanjeKorisnika_fk(
         streseeg.streseeg.StanjeKorisnika stanjeKorisnika_fk)
   {
      this.stanjeKorisnika_fk = stanjeKorisnika_fk;
   }

   public Izvjestaj(java.lang.Integer izvjestajId,
         streseeg.streseeg.StanjeKorisnika stanjeKorisnika_fk)
   {
      this.izvjestajId = izvjestajId;
      this.stanjeKorisnika_fk = stanjeKorisnika_fk;
   }

}