package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Korisnik implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Korisnik ID")
   private java.lang.Long korisnikId;
   @org.kie.api.definition.type.Label(value = "Ime")
   private java.lang.String ime;
   @org.kie.api.definition.type.Label(value = "Prezime")
   private java.lang.String prezime;
   @org.kie.api.definition.type.Label(value = "Korisnicko ime")
   private java.lang.String korisnickoIme;
   @org.kie.api.definition.type.Label(value = "Lozinka")
   private java.lang.String lozinka;
   @org.kie.api.definition.type.Label(value = "Godine")
   private java.lang.Integer godine;
   @org.kie.api.definition.type.Label(value = "Spol")
   private java.lang.String spol;

   public Korisnik()
   {
   }

   public java.lang.Long getKorisnikId()
   {
      return this.korisnikId;
   }

   public void setKorisnikId(java.lang.Long korisnikId)
   {
      this.korisnikId = korisnikId;
   }

   public java.lang.String getIme()
   {
      return this.ime;
   }

   public void setIme(java.lang.String ime)
   {
      this.ime = ime;
   }

   public java.lang.String getPrezime()
   {
      return this.prezime;
   }

   public void setPrezime(java.lang.String prezime)
   {
      this.prezime = prezime;
   }

   public java.lang.String getKorisnickoIme()
   {
      return this.korisnickoIme;
   }

   public void setKorisnickoIme(java.lang.String korisnickoIme)
   {
      this.korisnickoIme = korisnickoIme;
   }

   public java.lang.String getLozinka()
   {
      return this.lozinka;
   }

   public void setLozinka(java.lang.String lozinka)
   {
      this.lozinka = lozinka;
   }

   public java.lang.Integer getGodine()
   {
      return this.godine;
   }

   public void setGodine(java.lang.Integer godine)
   {
      this.godine = godine;
   }

   public java.lang.String getSpol()
   {
      return this.spol;
   }

   public void setSpol(java.lang.String spol)
   {
      this.spol = spol;
   }

   public Korisnik(java.lang.Long korisnikId, java.lang.String ime,
         java.lang.String prezime, java.lang.String korisnickoIme,
         java.lang.String lozinka, java.lang.Integer godine,
         java.lang.String spol)
   {
      this.korisnikId = korisnikId;
      this.ime = ime;
      this.prezime = prezime;
      this.korisnickoIme = korisnickoIme;
      this.lozinka = lozinka;
      this.godine = godine;
      this.spol = spol;
   }

}