package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class mobitelKorisnika implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Mobitel ID")
   private java.lang.Long mobitelId;
   @org.kie.api.definition.type.Label(value = "Broj mobitela ID")
   private java.lang.String brojMobitelaId;

   public mobitelKorisnika()
   {
   }

   public java.lang.Long getMobitelId()
   {
      return this.mobitelId;
   }

   public void setMobitelId(java.lang.Long mobitelId)
   {
      this.mobitelId = mobitelId;
   }

   public java.lang.String getBrojMobitelaId()
   {
      return this.brojMobitelaId;
   }

   public void setBrojMobitelaId(java.lang.String brojMobitelaId)
   {
      this.brojMobitelaId = brojMobitelaId;
   }

   public mobitelKorisnika(java.lang.Long mobitelId,
         java.lang.String brojMobitelaId)
   {
      this.mobitelId = mobitelId;
      this.brojMobitelaId = brojMobitelaId;
   }

}