package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MozdaniValoviMozga implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Mozdani valovi ID")
   private Integer mozdaniValoviId;

   @org.kie.api.definition.type.Label("Alpha")
   private java.lang.Integer alpha;

   @org.kie.api.definition.type.Label(value = "Beta")
   private java.lang.Integer beta;

   @org.kie.api.definition.type.Label(value = "Gamma")
   private java.lang.Integer gamma;

   public MozdaniValoviMozga()
   {
   }

   public java.lang.Integer getMozdaniValoviId()
   {
      return this.mozdaniValoviId;
   }

   public void setMozdaniValoviId(java.lang.Integer mozdaniValoviId)
   {
      this.mozdaniValoviId = mozdaniValoviId;
   }

   public java.lang.Integer getAlpha()
   {
      return this.alpha;
   }

   public void setAlpha(java.lang.Integer alpha)
   {
      this.alpha = alpha;
   }

   public java.lang.Integer getBeta()
   {
      return this.beta;
   }

   public void setBeta(java.lang.Integer beta)
   {
      this.beta = beta;
   }

   public java.lang.Integer getGamma()
   {
      return this.gamma;
   }

   public void setGamma(java.lang.Integer gamma)
   {
      this.gamma = gamma;
   }

   public MozdaniValoviMozga(java.lang.Integer mozdaniValoviId,
         java.lang.Integer alpha, java.lang.Integer beta, java.lang.Integer gamma)
   {
      this.mozdaniValoviId = mozdaniValoviId;
      this.alpha = alpha;
      this.beta = beta;
      this.gamma = gamma;
   }

}