package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Mozdani_valovi_mozga implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Mozdani_valovi_mozga() {
    }

}