package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MozdaniValoviMozga implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Vrijednost vala")
   private java.lang.Integer vrijednostVala;

   @org.kie.api.definition.type.Label("Mozdani valovi ID")
   private Integer mozdaniValoviId;

   @org.kie.api.definition.type.Label(value = "Alpha")
   private java.lang.Integer alpha;

   public MozdaniValoviMozga()
   {
   }

   public java.lang.Integer getVrijednostVala()
   {
      return this.vrijednostVala;
   }

   public void setVrijednostVala(java.lang.Integer vrijednostVala)
   {
      this.vrijednostVala = vrijednostVala;
   }

   public java.lang.Integer getMozdaniValoviId()
   {
      return this.mozdaniValoviId;
   }

   public void setMozdaniValoviId(java.lang.Integer mozdaniValoviId)
   {
      this.mozdaniValoviId = mozdaniValoviId;
   }

   public java.lang.Integer getAlpha()
   {
      return this.alpha;
   }

   public void setAlpha(java.lang.Integer alpha)
   {
      this.alpha = alpha;
   }

   public MozdaniValoviMozga(java.lang.Integer vrijednostVala,
         java.lang.Integer mozdaniValoviId, java.lang.Integer alpha)
   {
      this.vrijednostVala = vrijednostVala;
      this.mozdaniValoviId = mozdaniValoviId;
      this.alpha = alpha;
   }

}