package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObradeniValovi implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ObradeniValovi() {
    }

}