package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ocitavanjevalova implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Ocitavanje valova ID")
   private java.lang.Integer ocitavanjValovaId;
   @org.kie.api.definition.type.Label(value = "Ocitanost ID")
   private java.lang.Boolean ocitanostId;

   public Ocitavanjevalova()
   {
   }

   public java.lang.Integer getOcitavanjValovaId()
   {
      return this.ocitavanjValovaId;
   }

   public void setOcitavanjValovaId(java.lang.Integer ocitavanjValovaId)
   {
      this.ocitavanjValovaId = ocitavanjValovaId;
   }

   public java.lang.Boolean getOcitanostId()
   {
      return this.ocitanostId;
   }

   public void setOcitanostId(java.lang.Boolean ocitanostId)
   {
      this.ocitanostId = ocitanostId;
   }

   public Ocitavanjevalova(java.lang.Integer ocitavanjValovaId,
         java.lang.Boolean ocitanostId)
   {
      this.ocitavanjValovaId = ocitavanjValovaId;
      this.ocitanostId = ocitanostId;
   }

}