package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ocitavanjevalova implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Ocitavanje valova ID")
   private java.lang.Integer ocitavanjValovaId;
   @org.kie.api.definition.type.Label(value = "Ocitanost")
   private java.lang.Boolean ocitanost;

   public Ocitavanjevalova()
   {
   }

   public java.lang.Integer getOcitavanjValovaId()
   {
      return this.ocitavanjValovaId;
   }

   public void setOcitavanjValovaId(java.lang.Integer ocitavanjValovaId)
   {
      this.ocitavanjValovaId = ocitavanjValovaId;
   }

   public java.lang.Boolean getOcitanost()
   {
      return this.ocitanost;
   }

   public void setOcitanost(java.lang.Boolean ocitanost)
   {
      this.ocitanost = ocitanost;
   }

   public Ocitavanjevalova(java.lang.Integer ocitavanjValovaId,
         java.lang.Boolean ocitanost)
   {
      this.ocitavanjValovaId = ocitavanjValovaId;
      this.ocitanost = ocitanost;
   }

}