package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Odluka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Odluka ID")
   private Integer odlukaid;
   @org.kie.api.definition.type.Label("Odluka")
   private java.lang.Boolean odluka;

   @org.kie.api.definition.type.Label(value = "Stanje korisnika FK")
   private streseeg.streseeg.StanjeKorisnika stanjeKorisnika_fk;

   public Odluka()
   {
   }

   public java.lang.Boolean getOdluka()
   {
      return this.odluka;
   }

   public void setOdluka(java.lang.Boolean odluka)
   {
      this.odluka = odluka;
   }

   public java.lang.Integer getOdlukaid()
   {
      return this.odlukaid;
   }

   public void setOdlukaid(java.lang.Integer odlukaid)
   {
      this.odlukaid = odlukaid;
   }

   public streseeg.streseeg.StanjeKorisnika getStanjeKorisnika_fk()
   {
      return this.stanjeKorisnika_fk;
   }

   public void setStanjeKorisnika_fk(
         streseeg.streseeg.StanjeKorisnika stanjeKorisnika_fk)
   {
      this.stanjeKorisnika_fk = stanjeKorisnika_fk;
   }

   public Odluka(java.lang.Integer odlukaid, java.lang.Boolean odluka,
         streseeg.streseeg.StanjeKorisnika stanjeKorisnika_fk)
   {
      this.odlukaid = odlukaid;
      this.odluka = odluka;
      this.stanjeKorisnika_fk = stanjeKorisnika_fk;
   }

}