package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Odluka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Odluka ID")
   private java.lang.Long odlukaid;
   @org.kie.api.definition.type.Label(value = "Odluka")
   private java.lang.Boolean odluka;

   @org.kie.api.definition.type.Label(value = "Stanje korisnika ID")
   private java.lang.Long stanjeKorisnikaId;

   public Odluka()
   {
   }

   public java.lang.Long getOdlukaid()
   {
      return this.odlukaid;
   }

   public void setOdlukaid(java.lang.Long odlukaid)
   {
      this.odlukaid = odlukaid;
   }

   public java.lang.Boolean getOdluka()
   {
      return this.odluka;
   }

   public void setOdluka(java.lang.Boolean odluka)
   {
      this.odluka = odluka;
   }

   public java.lang.Long getStanjeKorisnikaId()
   {
      return this.stanjeKorisnikaId;
   }

   public void setStanjeKorisnikaId(java.lang.Long stanjeKorisnikaId)
   {
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

   public Odluka(java.lang.Long odlukaid, java.lang.Boolean odluka,
         java.lang.Long stanjeKorisnikaId)
   {
      this.odlukaid = odlukaid;
      this.odluka = odluka;
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

}