package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Odluka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Odluka ID")
   private java.lang.Long odlukaid;
   @org.kie.api.definition.type.Label(value = "Mozdani valovi ID")
   private java.lang.Long mozdaniValoviId;

   public Odluka()
   {
   }

   public java.lang.Long getOdlukaid()
   {
      return this.odlukaid;
   }

   public void setOdlukaid(java.lang.Long odlukaid)
   {
      this.odlukaid = odlukaid;
   }

   public java.lang.Long getMozdaniValoviId()
   {
      return this.mozdaniValoviId;
   }

   public void setMozdaniValoviId(java.lang.Long mozdaniValoviId)
   {
      this.mozdaniValoviId = mozdaniValoviId;
   }

   public Odluka(java.lang.Long odlukaid, java.lang.Long mozdaniValoviId)
   {
      this.odlukaid = odlukaid;
      this.mozdaniValoviId = mozdaniValoviId;
   }

}