package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PotvrdaUkljucivanjaSenzora implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Senzor info ID")
   private java.lang.Integer senzorInfoId;
   @org.kie.api.definition.type.Label(value = "Radi ID")
   private java.lang.Boolean radiId;

   public PotvrdaUkljucivanjaSenzora()
   {
   }

   public java.lang.Integer getSenzorInfoId()
   {
      return this.senzorInfoId;
   }

   public void setSenzorInfoId(java.lang.Integer senzorInfoId)
   {
      this.senzorInfoId = senzorInfoId;
   }

   public java.lang.Boolean getRadiId()
   {
      return this.radiId;
   }

   public void setRadiId(java.lang.Boolean radiId)
   {
      this.radiId = radiId;
   }

   public PotvrdaUkljucivanjaSenzora(java.lang.Integer senzorInfoId,
         java.lang.Boolean radiId)
   {
      this.senzorInfoId = senzorInfoId;
      this.radiId = radiId;
   }

}