package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Povezivanje")
public class Povezivanje implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Povezivanje ID")
   private java.lang.Integer povezivanjeId;
   @org.kie.api.definition.type.Label(value = "Povezanost")
   private java.lang.Boolean povezanost;

   public Povezivanje()
   {
   }

   public java.lang.Integer getPovezivanjeId()
   {
      return this.povezivanjeId;
   }

   public void setPovezivanjeId(java.lang.Integer povezivanjeId)
   {
      this.povezivanjeId = povezivanjeId;
   }

   public java.lang.Boolean getPovezanost()
   {
      return this.povezanost;
   }

   public void setPovezanost(java.lang.Boolean povezanost)
   {
      this.povezanost = povezanost;
   }

   public Povezivanje(java.lang.Integer povezivanjeId,
         java.lang.Boolean povezanost)
   {
      this.povezivanjeId = povezivanjeId;
      this.povezanost = povezanost;
   }

}