package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StanjeKorisnika implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Stanje korisnika ID")
   private Integer stanjeKorisnikaId;
   @org.kie.api.definition.type.Label("Mozdani valovi FK")
   private streseeg.streseeg.MozdaniValoviMozga mozdaniValovi_fk;

   @org.kie.api.definition.type.Label(value = "Osjecaj")
   private java.lang.Boolean osjecaj;

   public StanjeKorisnika()
   {
   }

   public java.lang.Integer getStanjeKorisnikaId()
   {
      return this.stanjeKorisnikaId;
   }

   public void setStanjeKorisnikaId(java.lang.Integer stanjeKorisnikaId)
   {
      this.stanjeKorisnikaId = stanjeKorisnikaId;
   }

   public streseeg.streseeg.MozdaniValoviMozga getMozdaniValovi_fk()
   {
      return this.mozdaniValovi_fk;
   }

   public void setMozdaniValovi_fk(
         streseeg.streseeg.MozdaniValoviMozga mozdaniValovi_fk)
   {
      this.mozdaniValovi_fk = mozdaniValovi_fk;
   }

   public java.lang.Boolean getOsjecaj()
   {
      return this.osjecaj;
   }

   public void setOsjecaj(java.lang.Boolean osjecaj)
   {
      this.osjecaj = osjecaj;
   }

   public StanjeKorisnika(java.lang.Integer stanjeKorisnikaId,
         streseeg.streseeg.MozdaniValoviMozga mozdaniValovi_fk,
         java.lang.Boolean osjecaj)
   {
      this.stanjeKorisnikaId = stanjeKorisnikaId;
      this.mozdaniValovi_fk = mozdaniValovi_fk;
      this.osjecaj = osjecaj;
   }

}