package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UkljucivanjeAplikacije implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public UkljucivanjeAplikacije() {
    }

}