package streseeg.streseeg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UkljucivanjeAplikacije implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Ukljucivanje aplikacije ID")
   private java.lang.Integer ukljucivanjeAplikacijeId;
   @org.kie.api.definition.type.Label(value = "Ukljucenost")
   private java.lang.Boolean ukljucenost;

   public UkljucivanjeAplikacije()
   {
   }

   public java.lang.Integer getUkljucivanjeAplikacijeId()
   {
      return this.ukljucivanjeAplikacijeId;
   }

   public void setUkljucivanjeAplikacijeId(
         java.lang.Integer ukljucivanjeAplikacijeId)
   {
      this.ukljucivanjeAplikacijeId = ukljucivanjeAplikacijeId;
   }

   public java.lang.Boolean getUkljucenost()
   {
      return this.ukljucenost;
   }

   public void setUkljucenost(java.lang.Boolean ukljucenost)
   {
      this.ukljucenost = ukljucenost;
   }

   public UkljucivanjeAplikacije(java.lang.Integer ukljucivanjeAplikacijeId,
         java.lang.Boolean ukljucenost)
   {
      this.ukljucivanjeAplikacijeId = ukljucivanjeAplikacijeId;
      this.ukljucenost = ukljucenost;
   }

}